# If you have any questions, you can add me on Discord: NoJokeFNA | Julian#4166
# or join our Discord: https://discord.gg/UHkUuFD

#--------------------------------------------
# Parameters:
# {PLAYER}      returns the player's name
# {DISPLAYNAME} returns the player's displayname
# {GROUPPLAYER} » Required LuckPerms, PermissionsEx or CloudNet « Only callback the group's prefix!

# If you activate 'bypass', the join/quit/kick message was not send

join:
  enable: true
  message: '&a{PLAYER} joined the server.'
  admin:
    permission: 'guild.join.admin'
    bypass: false

quit:
  enable: true
  message: '&c{PLAYER} has left the server.'
  admin:
    permission: 'guild.left.admin'
    bypass: false

kick:
  enable: true
  message: '&c{PLAYER} got kicked.'
  admin:
    permission: 'guild.kicked.admin'
    bypass: false
#--------------------------------------------

#--------------------------------------------
economy:
  # Declare the boolean, if you want to use economey [essentials] support
  # If you want to use your own economy system, you can use them via the GuildUpdateBank event
  use_economy_support: true
#--------------------------------------------

#--------------------------------------------
tablist:
  labymod:
    # Parameters:
    # {PLAYER}      returns the player's name
    # {DISPLAYNAME} returns the player's displayname
    # {GROUPPLAYER} » Required LuckPerms, PermissionsEx or CloudNet « Only callback the group's prefix!
    # {GUILD}       returns the player's guild

    # Use 'UpperCase' for [GUILD], 'lowerCase' for [guild] or 'normal' for [Guild]
    guild_format: 'normal'

    use_labymod: true
    subTitle_normal: '{GROUPPLAYER} {PLAYER}'
    subTitle_member: '{GROUPPLAYER} {PLAYER} &8- &c[{GUILD}] &aMember'
    subTitle_officer: '{GROUPPLAYER} {PLAYER} &8- &c[{GUILD}] &2Officer'
    subTitle_master: '{GROUPPLAYER} {PLAYER} &8- &c[{GUILD}] &6Master'


  use_header_footer: true
  header: '{NL}&7•&8● &cGuild &8●&7•{NL}&8➥ &7Coded by NoJokeFNA{NL}'
  footer: '&8╘ &7This server uses the &cGuild-System'

  # Use 'UpperCase' for [GUILD], 'lowerCase' for [guild] or 'normal' for [Guild]
  guild_format: 'normal'

  # If you activate this, you use permissions instead of groups
  # So, you can ignore the 'permission' path under your 'group' if you have deactivated this function
  use_permissions: false

  # 'admin'                  is your team name
  # '&4Admin &8| &4'         is for the tablist prefix
  # '&4Administrator &8| &4' is for the tablist prefix
  # '&8[&6{GUILD}&8]'        is behind your nametag
  # 'Admin'                  is the group which you need, when you've got LuckPerms, PermissionsEx or CloudPerms enabled
  # 'guild.tab.admin'        is is the permission you need, when you have activated 'use_permissions'
  # '01'                     is your rank position || 01 = Highest

  # Parameters:
  # {GUILD} return players guild

  use_tablist: true
  use_scoreboard: true

  prefix:
    admin:
      - '&4&lAdmin &8| &7'
      - '&4&lAdministrator &8| &7'
      - '&8[&6{GUILD}&8]'
      - 'Admin'
      - 'guild.tab.admin'
      - 01
    developer:
      - '&6&lDev &8| &7'
      - '&6&lDeveloper &8| &7'
      - '&8[&6{GUILD}&8]'
      - 'Developer'
      - 'guild.tab.developer'
      - 02
    premium:
      - '&3&lPremium &8| &7'
      - '&3&lPremium &8| &7'
      - '&8[&6{GUILD}&8]'
      - 'Premium'
      - 'guild.tab.premium'
      - 03
    default:
      - '&7Player &8| &7'
      - '&7Player &8| &7'
      - '&8[&6{GUILD}&8]'
      - 'default'
      - 'guild.tab.default'
      - 04
#--------------------------------------------

#--------------------------------------------
# Parameters:
# {NL} return new line

motd:
  use_motd: true
  text: '&8» &7This server uses the &cGuild-System{NL} &8╘ &7Coded by &cNoJokeFNA'

  use_max_players: true
  max_players: 45
#--------------------------------------------